version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api    
    depends_on:
      - motorent.database
      - motorent.kafka
      - messageconsumer
    container_name: motorent.api
    build:
      context: .
      dockerfile: Api/Dockerfile

  motorent.database:
    image: postgres:latest
    container_name: motorent.database
    environment:
     - POSTGRES_DB=MotoRent
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=12345678 
    volumes:
     - ./.containers/moto-db:/var/lib/postgresql/data
    ports:
     - 8432:5432
     
  motorent.zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  motorent.kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - motorent.zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: motorent.zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://motorent.kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  messageconsumer:
    image: ${DOCKER_REGISTRY-}messageconsumer
    depends_on:
      - motorent.kafka
      - motorent.database
    build:
      context: .
      dockerfile: MessageConsumer/Dockerfile

